### ISSUE TITLE
请问老师能看看我这个反OCR做的怎么样吗？感谢指导！

### ISSUE THREAD

**Issue by ghost** [Catherina0/FreeNetGuard#1]
老师您好，嗯我的构想是可以通过“波频”和“波幅”来到达干扰的目的。
感觉如果是通过点和线来干扰不太合适，重点的人类可以也识别不出来了，
目前是没见过可以在干扰OCR识别的情况下保证易读性的。

https://github.com/molikai-work/OCR-Interference

**Comment by Catherina0** [comment]
墨离，您好，很高兴能看到你提出的讨论，经过我的测试，MacBook Pro 在 14.2 (23C64) 系统下 可以识别80%的测试图片，由此可见，波频和波幅在一定程度上能干扰OCR，但是并不能很好的实现反OCR的功能。

对此，我提出以下的一些改进的观点
1. 还是保留一定量的点与线，但是将文字进行一定程度的扭曲变形
2. 将部分文字进行旋转，例如 将部分文字旋转-90～180度，这也是我未来的改进方向

对于易读性，我个人的观点是，在AI普遍被使用的情况下，易读性和反识别可能并不能共存。

**Comment by ghost** [comment]
谢谢老师的建议！
